### ISSUE TITLE
Button display: flex? 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#128]
https://github.com/trezor/trezor-ui-components/commit/dabf5cb40f824e2e992b1bf3c3f70df85b2ea227#diff-0c2221e8bf1fa0e8710e0df0f6829fc1R10

Should components have display set to flex? 

Personally I would expect basic building blocks to be either `inline` or `block`. 

We maybe could use `flex` but we would need to be consistent then? At this moment I believe that it would be better to stick to classic approach, but lets discuss it.

**Comment by keip** [comment]
IMO i would use `flex` for sure, because of easy centering and aligning of elements (vertically & horizontally) and this will also help us a lot with responsivity.

**Comment by mroz22** [comment]
Ok, I misunderstood flex a bit. Thought it was source of my probles and but it wasnt!
