### ISSUE TITLE
Add screen size to variables?

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#139]
To have consistent break poins, I would suggest adding screensize here: 

https://github.com/trezor/trezor-ui-components/blob/master/src/config/variables.js

Just like it is here

https://github.com/trezor/trezor-wallet/blob/master/src/config/variables.js

Or is it a bad idea?

**Comment by slowbackspace** [comment]
I am not sure if it is a good idea to force breakpoints. I would like to keep the ability for an app to handle responsivity on its own (eg setting custom breakpoints). 
Grommet handles this with theming
https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation
(eg `global.breakpoints.small.value` is set to `768px` and you can override it). I am sure we can do something similar, but I won't give you an ETA so feel free to send a PR :D

For now we don't have any grid system so breakpoints are not yet needed in TUC. There is only one component in TUC where we need to think about its responsivity (and we didn't yet) is `Notification` (later also `Header` component). 

So I would suggest that we leave breakpoints from TUC for now and later implement them via theming.

**Comment by slowbackspace** [comment]
Simple `SCREEN_SIZE` var added in https://github.com/trezor/trezor-ui-components/pull/173
No ETA for ability to specify custom breakpoints 😭
