### ISSUE TITLE
Make notification responsive

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-ui-components#146]
Should be button always "one-line"?
![image](https://user-images.githubusercontent.com/3112191/54915085-aba2b800-4ef6-11e9-8945-51a06f094bcd.png)

**Comment by slowbackspace** [comment]
Right now no. There is still work to be done to make notification responsive. Currently If we would force one-line button then on 320px screens there is going to be only 80px space left for text (it can be even worse in other languages) :)

I discussed how we could set breakpoints for responsive design in https://github.com/trezor/trezor-ui-components/issues/139
