### ISSUE TITLE
Header - react-router-dom

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#179]
Router uses react-router-dom 

https://github.com/trezor/trezor-ui-components/blob/dbfd1bf723d8b671aa06f189a501f2abaa3236e9/src/components/Header/index.js#L4

Which is a problem if should be used outside router context - renders following error 
```
You should not use <Route> or withRouter() outside a <Router>
```

**Comment by slowbackspace** [comment]
todo: https://stackoverflow.com/questions/41299203/pass-a-wrapper-component-as-props-in-reactjs
