### ISSUE TITLE
Remove duplicate select (async)

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-ui-components#25]
Select and AsyncSelect components share the same styles. I can't come up with good reason why keep them both in storybook. Maybe a note could be added to basic Select about the async version- instructions on how to import it from the lib, link to https://react-select.com/async for more info. Actually maybe we could provide similiar link to basic Select as well since our component is just a styling wrapper for the real thing (https://react-select.com).

<img width="274" alt="screenshot 2019-02-27 at 10 46 49" src="https://user-images.githubusercontent.com/6961901/53481213-0292aa00-3a7d-11e9-8414-9bc631674f1d.png">

**Comment by keip** [comment]
I don't see this as a problem because both selects are part of the same react-select component, so there is no duplicate styles or no problem with sharing the same styles.
The async select only has the `loadOptions` callback which is asynchronous.

**Comment by slowbackspace** [comment]
yup exactly my point! Visually it is the same thing. why would we need it twice in the menu?
If we have good reason for that feel free to close the issue :)

**Comment by keip** [comment]
Because when you are using async select it is `<AsyncSelect />` and when you use select it's just `<Select />`.
There are also some different params for async select (defaultOptions, cacheOptions, etc..)

**Comment by slowbackspace** [comment]
ad AsyncSelect: yup that's why I wanted to add the note about async select to basic select
ad props: yup but these params are part of the react-select library and do not interfere with styling, thats why I wanted to link their docs for more info. We probably don't want to document 3rd party lib params when it is irelevant to the UI.

anyway closing the issue.
