### ISSUE TITLE
Refactor headings

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-ui-components#33]
This lib defines H1-H4, but in the next wallet we also use span with custom styling (in summary/receive/send tabs) that should really be a heading (H3 or whatever). 
```
    font-size: ${FONT_SIZE.WALLET_TITLE};
    font-weight: ${FONT_WEIGHT.MEDIUM};
    color: ${colors.WALLET_TITLE};
    padding-bottom: 35px;
```
We should include this type of heading to TUC. That will probably require a bit of refactoring.

Screenshot from the next wallet:
<img width="304" alt="screenshot 2019-02-27 at 15 12 41" src="https://user-images.githubusercontent.com/6961901/53496337-29afa280-3aa2-11e9-8298-6f616a67d2f8.png">

**Comment by keip** [comment]
Or we can make a component Tabs? It will include all the design and functionality.
Because using headings in tabs is imo illogical. Heading should be always in the content.

**Comment by slowbackspace** [comment]
I probably worded it badly. It is not used directly in the tab. It is used as title under navigation/tab ("Podepsat zpravu on screenshot")
