### ISSUE TITLE
app entry point

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#4]
https://github.com/trezor/trezor-ui-components/blob/89e733b9b121b1ff6ba3d05bd6c9d75941ff60d1/package.json#L4

shouldn't here be `npm/index.js"
?

**Comment by vladimirvolek** [comment]
No there is no /npm folder in repository

![image](https://user-images.githubusercontent.com/3112191/52569183-dd613300-2e10-11e9-88b3-6e584042031d.png)

**Comment by mroz22** [comment]
Ok, just that I needed to change it to npm to make it work in other project (with current build setup)
