### ISSUE TITLE
global dependency

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#6]
should't we have all dependencies locked per project? 
For example this `run-s`? 
https://github.com/trezor/trezor-ui-components/blob/89e733b9b121b1ff6ba3d05bd6c9d75941ff60d1/package.json#L9

**Comment by vladimirvolek** [comment]
yes fixed here: https://github.com/trezor/trezor-ui-components/commit/b8b5141b9861f252bcab68895f69c51de94e79b1
