### ISSUE TITLE
Duplicate icon

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-ui-components#95]
Icon-check and Icon-success appear to be duplicate. Is it some kind of sugar syntax? :] 

https://github.com/trezor/trezor-ui-components/blob/7b9667cbf2f34062fc0475bb7c127eeb11b7c2ea/src/config/icons.js#L67-L69

https://github.com/trezor/trezor-ui-components/blob/7b9667cbf2f34062fc0475bb7c127eeb11b7c2ea/src/config/icons.js#L12-L14

**Comment by slowbackspace** [comment]
I took a look where are these used in the next wallet.
CHECKED is used in an Input component (when the component state is `success`) and in "set max" button
SUCCESS is used in wait for it... checkbox
🤷‍♀️ 
We probably should keep only one, most likely SUCCESS as it makes more sense.
